import type { Metadata } from "next";
import "../../styles/theme.scss";
//import "./globals.css";

export const metadata: Metadata = {
  title: "Next JS IOATask",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
